// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQwBnTsBSyaCiRrmGlVHHq2fmi0HmvPcY',
    appId: '1:1821128878:web:26c49e8c2a95e51e6ed53f',
    messagingSenderId: '1821128878',
    projectId: 'wordle-clone-aac21',
    authDomain: 'wordle-clone-aac21.firebaseapp.com',
    storageBucket: 'wordle-clone-aac21.firebasestorage.app',
    measurementId: 'G-27MNK1Q2ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUlTl6e5AQs2zAztjneV82c4GjTM8R1qg',
    appId: '1:1821128878:android:504965031e682d5c6ed53f',
    messagingSenderId: '1821128878',
    projectId: 'wordle-clone-aac21',
    storageBucket: 'wordle-clone-aac21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLJpDi8mKFH_fNRIDm1-XBvgtXOw-nFb8',
    appId: '1:1821128878:ios:5f39e232d883be636ed53f',
    messagingSenderId: '1821128878',
    projectId: 'wordle-clone-aac21',
    storageBucket: 'wordle-clone-aac21.firebasestorage.app',
    iosBundleId: 'com.example.wordleClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLJpDi8mKFH_fNRIDm1-XBvgtXOw-nFb8',
    appId: '1:1821128878:ios:5f39e232d883be636ed53f',
    messagingSenderId: '1821128878',
    projectId: 'wordle-clone-aac21',
    storageBucket: 'wordle-clone-aac21.firebasestorage.app',
    iosBundleId: 'com.example.wordleClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQwBnTsBSyaCiRrmGlVHHq2fmi0HmvPcY',
    appId: '1:1821128878:web:25795220da764ddf6ed53f',
    messagingSenderId: '1821128878',
    projectId: 'wordle-clone-aac21',
    authDomain: 'wordle-clone-aac21.firebaseapp.com',
    storageBucket: 'wordle-clone-aac21.firebasestorage.app',
    measurementId: 'G-LSH9G88ZVQ',
  );
}
